import { z } from "zod";
import { repoPath, listDir, isDirectory, readTextFile } from "../repo.js";
import { join } from "path";

export const getArchitectureSchema = z.object({
  section: z.enum(["overview", "patterns", "tech_stack", "dependencies", "all"]).optional().default("all"),
});

export type GetArchitectureInput = z.infer<typeof getArchitectureSchema>;

function getOverview(): string {
  return `# Web Wallet Architecture Overview

## Stack
- **Next.js** (Pages Router) with TypeScript
- **React** with hooks and context for state management
- No Redux — state is managed via React Context + custom hooks

## Project Layout (src/)
- \`pages/\` — Next.js pages + API routes (file-based routing)
- \`features/\` — Feature-specific logic modules
- \`components/\` — Reusable React components, organized by domain
- \`hooks/\` — Shared custom React hooks
- \`contexts/\` — React context providers for global state
- \`models/\` — Shared TypeScript interfaces and types
- \`generated/openapi/\` — Orval-generated type-safe API fetchers (from OpenAPI specs)
- \`utils/\` — Utility functions
- \`openapi/\` (root) — OpenAPI spec files used to generate API types

## Data Flow
1. **Pages** are entry points — they compose components and provide contexts
2. **Components** render UI and call hooks for data and actions
3. **Custom hooks** orchestrate API calls and local state
4. **API layer** uses Orval-generated fetchers for type-safe HTTP calls
5. **Firebase Remote Config** controls feature flags at runtime

## Key Integration Points
- **Authentication**: contexts provide auth state; \`pages/auth/\` handles login flows
- **i18n**: \`react-intl\` + \`global.translations.ts\` for all user-facing strings
- **API types**: Generated by Orval from \`openapi/*.yaml\` → \`src/generated/openapi/\`
- **Middleware**: \`src/middleware.ts\` intercepts requests for auth and redirects
`;
}

function getPatterns(): string {
  return `# Key Patterns

## 1. React Context + Custom Hooks (State Management)
- No Redux. State is shared via React Context (\`createContext\`, \`useContext\`)
- Contexts live in \`src/contexts/\` or co-located with features
- Custom hooks abstract data fetching and state logic from components
- Typical hook shape: returns \`{ data, loading, error }\` + action callbacks

## 2. Orval API Layer
- All backend APIs are described in OpenAPI specs in \`openapi/\`
- Orval generates type-safe axios fetchers into \`src/generated/openapi/\`
- Components/hooks import generated fetchers directly — no manual HTTP calls
- Custom axios instance in \`src/utils/orval/\` adds auth headers + error handling

## 3. Feature Flag Pattern (Firebase Remote Config)
- Firebase Remote Config provides boolean/string flags
- Flags are read via custom hooks that wrap the Firebase SDK
- Feature-gated components check flags before rendering

## 4. i18n (react-intl)
- All user-visible strings live as keys in \`src/global.translations.ts\`
- Components use \`useIntl()\` hook or \`<FormattedMessage>\` component
- Translation files per locale in \`src/languages/\`

## 5. Next.js Routing
- File-based routing via \`src/pages/\`
- \`src/middleware.ts\` runs on matched routes for auth guards
- Dynamic routes use \`[param]\` and \`[...slug]\` file naming
- API routes under \`src/pages/api/\` expose Next.js serverless functions
`;
}

function getTechStack(): string {
  return `# Technology Stack

## Core Framework
- **Next.js** — SSR/CSR/ISR, file-based routing, API routes
- **React** (hooks, context) — UI layer
- **TypeScript** — Language

## Styling
- **Emotion** (CSS-in-JS) — Component-level styles

## API & Data
- **axios** — HTTP client
- **Orval** — Generates TypeScript fetchers from OpenAPI specs
- **OpenAPI / YAML** — API spec format in \`openapi/\`

## Auth & Flags
- **Firebase** — Remote Config (feature flags), Auth

## i18n
- **react-intl** — Internationalisation
- Translation key registry: \`src/global.translations.ts\`

## Testing
- **Jest** — Unit + integration tests
- **Cypress** — E2E tests (\`cypress/\`)
- **Storybook** — Component development + visual tests

## Build
- **TypeScript compiler** (tsc)
- **Next.js build** (webpack/turbopack internally)
- \`eslint\` for linting
`;
}

async function buildDependencyMap(): Promise<string> {
  const areas = ["pages", "features", "components", "hooks"];
  const lines: string[] = ["# Cross-Area Import Dependencies\n"];

  for (const area of areas) {
    const areaDir = repoPath("src", area);
    const topDirs = await listDir(areaDir);

    for (const topDir of topDirs) {
      const full = join(areaDir, topDir);
      if (!(await isDirectory(full))) continue;

      let content = "";
      const entries = await listDir(full);
      for (const e of entries) {
        if (e.endsWith(".tsx") || e.endsWith(".ts")) {
          try { content = await readTextFile(join(full, e)); break; } catch { /**/ }
        }
      }
      if (!content) continue;

      const imports = content.matchAll(/from ['"]\.\.\/(\w+)/g);
      const external = new Set<string>();
      for (const m of imports) {
        if (areas.includes(m[1]) && m[1] !== area) external.add(m[1]);
      }

      if (external.size > 0) {
        lines.push(`  src/${area}/${topDir} → imports from: ${[...external].join(", ")}`);
      }
    }
  }

  if (lines.length === 1) lines.push("  (No cross-area imports detected in sampled files)");
  return lines.join("\n");
}

export async function getArchitecture(input: GetArchitectureInput): Promise<string> {
  const sections: string[] = [];
  const s = input.section;
  if (s === "all" || s === "overview") sections.push(getOverview());
  if (s === "all" || s === "patterns") sections.push(getPatterns());
  if (s === "all" || s === "tech_stack") sections.push(getTechStack());
  if (s === "all" || s === "dependencies") sections.push(await buildDependencyMap());
  return sections.join("\n\n---\n\n");
}
